name: "setup-masm"
description: "Helps set up MASM into PATH for later usage."
author: "Gonçalo Carvalho"
branding:
  color: red
  icon: terminal
inputs:
  vswhere-path:
    required: false
    description: "Folder location of where vswhere.exe is located if a self-hosted agent"
  vs-version:
    description: "Version of Visual Studio to search; defaults to latest if not specified"
    required: false
  vs-prerelease:
    description: "Enable searching for pre-release versions of Visual Studio/MSBuild"
    required: false
  vs-architecture:
    description: "The preferred processor architecture of MASM. Can be either 'x86', 'x64' or 'arm64'. 'x64' is only available from Visual Studio version 17.0 and later."
    required: false
    default: "x64"
outputs:
  masmPath:
    description: "The resulting location of ml (x86), ml64 (x64) or armasm64 (arm64) for your inputs"

runs:
  using: "node20"
  main: "dist/index.js"
